### ISSUE TITLE
ADatePicker 无法使用

### ISSUE THREAD

**Issue by transtone** [x-extends/vxe-table-plugin-antd#10]
### 可复现的链接：

s

### 问题描述与截图：

日期弹窗之后，无法点击。点击任何地方都会关闭弹窗。

### 操作系统：

windows 10

### 浏览器版本：

edge  96.0.1054.41

### vue 版本：

3.2.23

### vxe-table 版本：

4.1.16

**Comment by transtone** [comment]
`antdv-2.2.8` 这个版本可用。

`antdv-3.x` 版本异常。

**Comment by DoubleRayWang** [comment]
遇到了同样的问题，报错信息里有关于dayjs的问题

**Comment by transtone** [comment]
`vxe-table-4.1.21`， `antdv-3.0.0-beta10`
无法获取 `a-date-picker` 的点击事件。

**Comment by transtone** [comment]
https://github.com/x-extends/vxe-table-plugin-antd/issues/9

**Comment by transtone** [comment]
https://vxetable.cn/other4/#/table/other/antd
官方示例可复现。

**Comment by kiss758** [comment]
遇到了同样的问题了

**Comment by kiss758** [comment]
"vxe-table-plugin-antd": "^3.0.9", 这个版本好像已修复，可用

**Comment by transtone** [comment]
> "vxe-table-plugin-antd": "^3.0.9", 这个版本好像已修复，可用

确实已经修复。这么重要的修复版本，居然放到 next 里，不来这里看一眼都不知道有这个版本。
