### ISSUE TITLE
使用 ADatePicker 报错

### ISSUE THREAD

**Issue by FreeRide-Joe** [x-extends/vxe-table-plugin-antd#8]
**（必填）请填写问题描述或截图：**

按 [文档](https://xuliangzhan_admin.gitee.io/vxe-table/v4/table/plugin/antdConfig) 配置如下：

`{ field: 'date1', title: 'ADatePicker', width: 140, editRender: { name: 'ADatePicker', props: { type: 'date', format: 'YYYY/MM/DD' } } }`

```
function getDatePickerCellValue(renderOpts, params, defaultFormat) {
  var _renderOpts$props5 = renderOpts.props,
      props = _renderOpts$props5 === void 0 ? {} : _renderOpts$props5;
  var row = params.row,
      column = params.column;

  var cellValue = _xeUtils["default"].get(row, column.property);

  if (cellValue) {
    cellValue = cellValue.format(props.format || defaultFormat);
  }

  return cellValue;
}
```

**`data1` 传入参数为 `string` 时，`getDatePickerCellValue` 中  `cellValue.format` 报错**

- OS: Windows 10
- Browser: Chrome  91.0.4472.164
- vue: 3.2.2
- vxe-table: 4.0.25

**Comment by llzzii** [comment]
哈喽，麻烦问下这个问题你解决了么@ @kt3721
